// Custom next/image loader. Active only when NEXT_PUBLIC_IMAGE_CDN is set (see
// next.config.mjs — local dev + Netlify leave it unset and use the built-in
// optimizer instead).
//
// On Cloudflare the Worker can't run sharp, so event images are pre-generated as
// responsive WebP and stored in R2, served at
//   https://img.vegaskiddos.com/event/<id>/<width>.webp
// (see lib/data.ts + tools/sync-images.mjs). event.image points at the 1024
// variant; this loader rewrites the width segment to the nearest generated size
// so <Image> gets an appropriately-sized file served straight from R2 — no
// runtime optimization, no ephemeral URLs.

// Must mirror the SIZES generated by tools/sync-images.mjs.
const SIZES = [384, 640, 1024, 1600];

export default function imageLoader({
  src,
  width,
  quality,
}: {
  src: string;
  width: number;
  quality?: number;
}): string {
  const cdn = process.env.NEXT_PUBLIC_IMAGE_CDN?.replace(/\/$/, "");

  // Durable R2 image: .../event/<id>/<size>.webp → swap <size> for the nearest
  // generated width (clamped to the largest available).
  if (cdn && src.startsWith(cdn) && /\/\d+\.webp$/.test(src)) {
    const pick = SIZES.find((s) => s >= width) ?? SIZES[SIZES.length - 1];
    return src.replace(/\/\d+\.webp$/, `/${pick}.webp`);
  }

  // Fallback: built-in optimizer (Netlify Image CDN in prod, sharp in dev).
  return `/_next/image?url=${encodeURIComponent(src)}&w=${width}&q=${quality || 75}`;
}
