import type { KidEvent } from "./types";

// Seed data — realistic Las Vegas family events used until Airtable is connected.
// Dates are generated relative to "now" so the app always shows upcoming events.

function daysFromNow(days: number, hour = 10, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const MOCK_EVENTS: KidEvent[] = [
  {
    id: "storytime-summerlin",
    title: "Baby & Me Storytime",
    description:
      "Songs, rhymes, and gentle stories designed for the littlest listeners and their grown-ups. A calm, sensory-friendly start to the morning.",
    venue: "Summerlin Library",
    address: "1771 Inner Circle Dr, Las Vegas, NV 89134",
    neighborhood: "summerlin",
    lat: 36.1735,
    lng: -115.3268,
    start: daysFromNow(1, 10, 0),
    end: daysFromNow(1, 10, 45),
    ageTiers: ["baby", "toddler"],
    priceTier: "free",
    priceText: "Free",
    url: "https://lvccld.org/",
    source: "Library",
    indoor: true,
  },
  {
    id: "discovery-museum-play",
    title: "Toddler Town Open Play",
    description:
      "Three floors of hands-on exhibits with a dedicated toddler zone for climbing, building, and water play. Strollers welcome.",
    venue: "DISCOVERY Children's Museum",
    address: "360 Promenade Pl, Las Vegas, NV 89106",
    neighborhood: "downtown",
    lat: 36.1716,
    lng: -115.1503,
    start: daysFromNow(2, 9, 30),
    end: daysFromNow(2, 16, 0),
    ageTiers: ["toddler", "kids"],
    priceTier: "mid",
    priceText: "$18.50 / person, under 1 free",
    url: "https://www.discoverykidslv.org/",
    source: "Venue",
    indoor: true,
  },
  {
    id: "springs-preserve-trails",
    title: "Family Nature Walk & Butterfly Habitat",
    description:
      "Guided stroll through the Springs Preserve trails ending at the seasonal butterfly habitat. Great for curious kids who love bugs and blooms.",
    venue: "Springs Preserve",
    address: "333 S Valley View Blvd, Las Vegas, NV 89107",
    neighborhood: "downtown",
    lat: 36.1709,
    lng: -115.1816,
    start: daysFromNow(3, 9, 0),
    end: daysFromNow(3, 11, 0),
    ageTiers: ["kids", "tweens"],
    priceTier: "under10",
    priceText: "$9.95 / child",
    url: "https://www.springspreserve.org/",
    source: "Venue",
    indoor: false,
  },
  {
    id: "henderson-lego-club",
    title: "LEGO Builders Club",
    description:
      "Drop-in building challenges with thousands of bricks. New theme every week — bring your imagination, we bring the LEGO.",
    venue: "Henderson Library — Green Valley",
    address: "2797 N Green Valley Pkwy, Henderson, NV 89014",
    neighborhood: "henderson",
    lat: 36.0639,
    lng: -115.0586,
    start: daysFromNow(4, 15, 30),
    end: daysFromNow(4, 16, 30),
    ageTiers: ["kids"],
    priceTier: "free",
    priceText: "Free",
    url: "https://hendersonlibraries.com/",
    source: "Library",
    indoor: true,
  },
  {
    id: "north-lv-splash",
    title: "Toddler Splash Hour",
    description:
      "The shallow leisure pool opens early just for the under-5 crowd. Lifeguards on duty, zero-depth entry, warm water.",
    venue: "Craig Ranch Regional Park Pool",
    address: "628 W Craig Rd, North Las Vegas, NV 89032",
    neighborhood: "north-lv",
    lat: 36.2389,
    lng: -115.1372,
    start: daysFromNow(5, 9, 0),
    end: daysFromNow(5, 10, 30),
    ageTiers: ["baby", "toddler"],
    priceTier: "under10",
    priceText: "$3 / child",
    url: "https://www.cityofnorthlasvegas.com/",
    source: "Parks & Rec",
    indoor: false,
  },
  {
    id: "southwest-art-jam",
    title: "Messy Art Jam",
    description:
      "Smocks on! Finger paints, giant paper, and zero rules. A gloriously messy creative session — we handle the cleanup.",
    venue: "Desert Breeze Community Center",
    address: "8275 Spring Mountain Rd, Las Vegas, NV 89147",
    neighborhood: "southwest",
    lat: 36.1261,
    lng: -115.2683,
    start: daysFromNow(6, 10, 0),
    end: daysFromNow(6, 11, 30),
    ageTiers: ["toddler", "kids"],
    priceTier: "under10",
    priceText: "$5 / child",
    url: "https://www.clarkcountynv.gov/",
    source: "Parks & Rec",
    indoor: true,
  },
  {
    id: "summerlin-farmers-market",
    title: "Downtown Summerlin Kids' Market Morning",
    description:
      "Family-friendly farmers market with a petting zoo, balloon artist, and live music. Free to wander, treats available to buy.",
    venue: "Downtown Summerlin",
    address: "1980 Festival Plaza Dr, Las Vegas, NV 89135",
    neighborhood: "summerlin",
    lat: 36.1591,
    lng: -115.3289,
    start: daysFromNow(7, 9, 0),
    end: daysFromNow(7, 13, 0),
    ageTiers: ["baby", "toddler", "kids", "tweens"],
    priceTier: "free",
    priceText: "Free admission",
    url: "https://www.downtownsummerlin.com/",
    source: "Community",
    indoor: false,
  },
  {
    id: "tween-coding-henderson",
    title: "Tween Coding Lab: Build Your First Game",
    description:
      "Hands-on intro to Scratch where tweens build a playable game in 90 minutes. Laptops provided; no experience needed.",
    venue: "Henderson Library — Paseo Verde",
    address: "280 S Green Valley Pkwy, Henderson, NV 89012",
    neighborhood: "henderson",
    lat: 36.0258,
    lng: -115.0853,
    start: daysFromNow(8, 16, 0),
    end: daysFromNow(8, 17, 30),
    ageTiers: ["tweens"],
    priceTier: "free",
    priceText: "Free — registration required",
    url: "https://hendersonlibraries.com/",
    source: "Library",
    indoor: true,
  },
  {
    id: "natural-history-dino",
    title: "Dino Discovery Day",
    description:
      "Meet the animatronic dinosaurs, dig for fossils in the kids' excavation pit, and take home a real shark tooth.",
    venue: "Las Vegas Natural History Museum",
    address: "900 Las Vegas Blvd N, Las Vegas, NV 89101",
    neighborhood: "downtown",
    lat: 36.1797,
    lng: -115.1389,
    start: daysFromNow(9, 10, 0),
    end: daysFromNow(9, 15, 0),
    ageTiers: ["kids", "tweens"],
    priceTier: "under10",
    priceText: "$10 / child",
    url: "https://www.lvnhm.org/",
    source: "Venue",
    indoor: true,
  },
  {
    id: "north-lv-music",
    title: "Music & Movement for Littles",
    description:
      "Shakers, scarves, and bubbles! A high-energy 45 minutes of dancing and singing for babies and toddlers.",
    venue: "North Las Vegas Library",
    address: "2300 Civic Center Dr, North Las Vegas, NV 89030",
    neighborhood: "north-lv",
    lat: 36.2076,
    lng: -115.1233,
    start: daysFromNow(10, 10, 30),
    end: daysFromNow(10, 11, 15),
    ageTiers: ["baby", "toddler"],
    priceTier: "free",
    priceText: "Free",
    url: "https://lvccld.org/",
    source: "Library",
    indoor: true,
  },
  {
    id: "summerlin-pumpkin",
    title: "Family Stargazing Night",
    description:
      "Telescopes set up by the local astronomy club. Hot cocoa, constellation hunts, and a story under the desert sky.",
    venue: "Summerlin Trails Park",
    address: "2010 Crossbridge Dr, Las Vegas, NV 89134",
    neighborhood: "summerlin",
    lat: 36.1822,
    lng: -115.3315,
    start: daysFromNow(11, 19, 30),
    end: daysFromNow(11, 21, 0),
    ageTiers: ["kids", "tweens"],
    priceTier: "free",
    priceText: "Free",
    source: "Community",
    indoor: false,
  },
  {
    id: "southwest-puppet-show",
    title: "Puppet Theater: The Three Little Pigs",
    description:
      "A 30-minute interactive puppet show with a craft to follow. Kids help huff and puff! Seating is on the floor — bring a blanket.",
    venue: "Windmill Library",
    address: "7060 W Windmill Ln, Las Vegas, NV 89113",
    neighborhood: "southwest",
    lat: 36.0438,
    lng: -115.2497,
    start: daysFromNow(12, 11, 0),
    end: daysFromNow(12, 12, 0),
    ageTiers: ["toddler", "kids"],
    priceTier: "free",
    priceText: "Free",
    url: "https://lvccld.org/",
    source: "Library",
    indoor: true,
  },
];
